version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: main
      POSTGRES_DBNAME: main
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: 'backend.dockerfile'
    ports:
      - '8000:8000'
